spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bigdatacenter.mysql.rds.aliyuncs.com:3306/rawdata_db
    username: rawdatauser
    password: rawdatauser@1234

